# Notebook Tips

- Shift + Tab next to a method to show Docstrings.  
- Tab after an object. to see available fields/methods.


# NumPy Arrays

In [ ]:
import numpy as np

In [2]:
list = [1, 2, 3]

In [4]:
list # python list

[1, 2, 3]

In [3]:
np.array(list) # numpy array, realize the differences of the two outputs

array([1, 2, 3])

In [5]:
nested_list = [[1, 2], [3, 4], [5, 6]] # two dimensional arrays

In [6]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [7]:
np.array(nested_list) # matrices, can realize how many dimensions by looking at how many consercutive [[]]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
#typically we don't transform python objects into numpy array, generate using numpy methods instead

In [10]:
np.arange(0, 10) # press Shift + Tab to see Docstring

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3) # floating point precision number

array([0., 0., 0.])

In [13]:
np.zeros((4,4)) #4x4 shape 2D matrices

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((4,10)) # (4, 10) python tuple object

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
np.linspace(0, 10, 3) # Returns `num` evenly spaced samples, calculated over the interval [`start`, `stop`].

array([ 0.,  5., 10.])

In [22]:
np.linspace(0, 10, 10) #include stop value


array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [23]:
np.eye(5) # Identity matrix. Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# UNIFORM DISTRIBUTION
# Create an array of the given shape and populate it with
# random samples from a uniform distribution
# over ``[0, 1)``.
np.random.rand(2)

array([0.51999516, 0.81605092])

In [27]:
np.random.rand(3, 4) #2D matrix with 3 rows 4 columns between 0 and 1. Notice that the parameters aren't in tuple form

array([[0.39620171, 0.48368702, 0.26720291, 0.45227539],
       [0.07504903, 0.04790027, 0.79328187, 0.03327744],
       [0.51283889, 0.87332591, 0.75553595, 0.34740715]])

In [28]:
# STANDARD NORMAL DISTRIBUTION
np.random.randn(5)

array([-1.58007616,  0.33993744,  1.92292156,  0.63746778,  0.42784779])

In [29]:
np.random.randint(0, 100)

7

In [31]:
# this guarantee same random numbers are generate 
# given that same parameters are passed in from different calls/computers
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [44]:
reshape_me = np.arange(0, 25)

In [45]:
reshape_me

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
reshape_me.shape # only 1D defined 

(25,)

In [54]:
reshaped = reshape_me.reshape(5, 5) # Returns an array containing the same data with a new shape.

In [56]:
reshape_me

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
reshaped.shape

(5, 5)

In [38]:
rand_arr = np.random.randint(0, 100, 10)

In [39]:
rand_arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [41]:
rand_arr.reshape(2, 5)

array([[82, 86, 74, 74, 87],
       [99, 23,  2, 21, 52]])

In [58]:
rand_arr.max()

99

In [59]:
rand_arr.argmax() # Return indices of the maximum values along the given axis.

5

In [60]:
rand_arr.min()

2

In [61]:
rand_arr.argmin()

7

In [63]:
rand_arr.dtype #64bit integer datatype

dtype('int64')